### ISSUE TITLE
uncompress the compressed output?

### ISSUE THREAD

**Issue by aloksharma1** [UweKeim/ZetaProducerHtmlCompressor#4]
hi,
i have a rare condition where i want to unminify &beautify the compressed html output when showing in textarea. is this possible using this compressor or some place else?

thanks

**Comment by UweKeim** [comment]
Maybe you can use something like HtmlAgilityPack to read-in the HTML as XML and then output it formatted again.

**Comment by aloksharma1** [comment]
thanks i will try that , i need to do this for js/css and html all .
