### ISSUE TITLE
Do you have any plan to port the library to .NET Core / .NET Standard?

### ISSUE THREAD

**Issue by happywisepaul** [UweKeim/ZetaProducerHtmlCompressor#8]
Do you have any plan to port the library to .NET Core / .NET Standard?  Currently when used in a .NET Core project there is a NU1701 warning: 

> Package 'ZetaProducerHtmlCompressor 1.0.3' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.

**Comment by UweKeim** [comment]
I think I can do it.

**Comment by UweKeim** [comment]
[Added a .NET Standard NuGet package](https://www.nuget.org/packages/ZetaProducerHtmlCompressorStandard/).
